before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: gZntj1imweYmDMGsI7iVcrdT/DlXsDZOO6QHcR+tqJ1r70SFm6SNFc6zKtnQFDgIuEYBfv3q9iqtIYsOMLGtBunPsuT47ZCWSf8hJiSTVAz4cs8NHMsvTztS+cCCrFyyTFsVVkoe5DjbdgMZMfNymtZaLJyhfnY9aO+BNUJAxQ/BMV9p3COW5gs7HBrzKiTWstnoNBcsm/AuxMJgNQG5mItxLODiL3yANIBb41OYcrZEk6jjUEOmQ5/3R8/B1C1qjy02QZiaB0rWhURmev8/9GJoCkaaAAtq0YTNDKr6ffbt3yqmazI3fM7/gCAEJjo8vBhwwRQZVHE/H2nSjhuoex8BeS0rHfS3WdJHzWMBLobys5GiRFCfYlO2OJCsA+ZXT6WZc8U1UDTiubEXBsvNjaK4EplaCifiCIU81Nacsd2uQYei386thV0Dim0+0933lzfWoxgCYm3SNUSAyac7GGoPdGTmM8zHxQ2AiMHDpw44WeCI56L6lFYCR7PSlli4Tion8iIvKv5KsF5h2l4TjAiNl/VoyEVcNSneRBvvzWbkPl/T+sFh4Cila9kPKSX90wBAz1LMbRsgdnCQMhjQ3kX3RNh5FomjO3SfAqKXao9SBmnYoUouWoVnsw54UEeIbTYm4dk0MMyTg4WKcx4DovKnM36X356OgYyqQ+FVB+Q= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
